version: "3.8"

services:
  api:
    build: ./backend
    command: uvicorn main:app --reload --host 0.0.0.0
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
  web:
    build: ./frontend
    command: npm run start
    ports:
      - 3000:3000
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
